name: CI

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-14
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: latest
    - name: Build and Test
      run: make ci
